"""initial schema

Revision ID: ced71cc956f3
Revises: 
Create Date: 2026-08-16 00:34:26.176534
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # used by the JSONB variant below
from sqlalchemy.dialects import postgresql

revision = 'ced71cc956f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_slug'), ['slug'], unique=True)

    op.create_table('children',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('avatar', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_children_family_id'), ['family_id'], unique=False)

    op.create_table('milestones',
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.Enum('concepts_mastered', 'vocabulary_estimate', 'skill_mastered', 'streak', name='milestonekind', native_enum=False, length=30), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_milestones_subject_id'), ['subject_id'], unique=False)

    op.create_table('parents',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parents_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_parents_family_id'), ['family_id'], unique=False)

    op.create_table('skills',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('parent_skill_id', sa.Uuid(), nullable=True),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('child_name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'slug', name='uq_skill_subject_slug')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_parent_skill_id'), ['parent_skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_subject_id'), ['subject_id'], unique=False)

    op.create_table('child_milestones',
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('milestone_id', sa.Uuid(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'milestone_id', name='uq_child_milestone')
    )
    with op.batch_alter_table('child_milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_child_milestones_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_child_milestones_milestone_id'), ['milestone_id'], unique=False)

    op.create_table('concepts',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('primary_skill_id', sa.Uuid(), nullable=True),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('frequency_band', sa.Integer(), nullable=True),
    sa.Column('media', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'slug', name='uq_concept_subject_slug')
    )
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concepts_frequency_band'), ['frequency_band'], unique=False)
        batch_op.create_index(batch_op.f('ix_concepts_primary_skill_id'), ['primary_skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_concepts_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_concepts_subject_id'), ['subject_id'], unique=False)

    op.create_table('learner_skill_states',
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('ability', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'skill_id', name='uq_learner_skill')
    )
    with op.batch_alter_table('learner_skill_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learner_skill_states_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learner_skill_states_skill_id'), ['skill_id'], unique=False)

    op.create_table('learner_subject_states',
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('ability', sa.Float(), nullable=False),
    sa.Column('concepts_mastered', sa.Integer(), nullable=False),
    sa.Column('vocabulary_estimate', sa.Integer(), nullable=True),
    sa.Column('vocabulary_confidence', sa.Float(), nullable=True),
    sa.Column('vocabulary_band', sa.String(length=40), nullable=True),
    sa.Column('diagnostic_completed', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'subject_id', name='uq_learner_subject')
    )
    with op.batch_alter_table('learner_subject_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learner_subject_states_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learner_subject_states_subject_id'), ['subject_id'], unique=False)

    op.create_table('learning_sessions',
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('target_skill_id', sa.Uuid(), nullable=True),
    sa.Column('session_type', sa.Enum('diagnostic', 'practice', 'review', 'challenge', 'mixed', name='sessiontype', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'abandoned', name='sessionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_questions', sa.Integer(), nullable=False),
    sa.Column('questions_presented', sa.Integer(), nullable=False),
    sa.Column('questions_correct', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_sessions_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_sessions_subject_id'), ['subject_id'], unique=False)

    op.create_table('concept_prerequisites',
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('prerequisite_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('concept_id', 'prerequisite_id')
    )
    op.create_table('concept_skills',
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('concept_id', 'skill_id')
    )
    op.create_table('events',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_event_child_name', ['child_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_session_id'), ['session_id'], unique=False)

    op.create_table('learner_concept_states',
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('dimension', sa.Enum('recognition', 'meaning', 'context', 'spelling', name='dimension', native_enum=False, length=20), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('unknown', 'introduced', 'learning', 'developing', 'mastered', 'needs_review', name='masterystatus', native_enum=False, length=20), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('hint_usage', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('average_response_time_ms', sa.Float(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_correct_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_interval_days', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'concept_id', 'dimension', name='uq_learner_concept_dimension')
    )
    with op.batch_alter_table('learner_concept_states', schema=None) as batch_op:
        batch_op.create_index('ix_learner_concept_due', ['child_id', 'next_review_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learner_concept_states_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learner_concept_states_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learner_concept_states_next_review_at'), ['next_review_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learner_concept_states_status'), ['status'], unique=False)

    op.create_table('questions',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=True),
    sa.Column('concept_id', sa.Uuid(), nullable=True),
    sa.Column('question_type', sa.Enum('multiple_choice', 'image_choice', 'text_input', 'spelling', 'true_false', 'ordering', 'matching', 'audio_response', 'numeric_input', name='questiontype', native_enum=False, length=32), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('observed_difficulty', sa.Float(), nullable=True),
    sa.Column('observed_attempts', sa.Integer(), nullable=False),
    sa.Column('observed_correct', sa.Integer(), nullable=False),
    sa.Column('age_min', sa.Integer(), nullable=False),
    sa.Column('age_max', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('answer', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('hints', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('media', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'review', 'approved', 'published', 'retired', name='contentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_question_type'), ['question_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_subject_id'), ['subject_id'], unique=False)

    op.create_table('rewards',
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rewards_child_id'), ['child_id'], unique=False)

    op.create_table('question_attempts',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=True),
    sa.Column('skill_id', sa.Uuid(), nullable=True),
    sa.Column('dimension', sa.Enum('recognition', 'meaning', 'context', 'spelling', name='dimension', native_enum=False, length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_answer', sa.Text(), nullable=True),
    sa.Column('normalized_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('hint_used', sa.Boolean(), nullable=False),
    sa.Column('hint_level', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('difficulty_at_attempt', sa.Float(), nullable=True),
    sa.Column('mastery_before', sa.Float(), nullable=True),
    sa.Column('mastery_after', sa.Float(), nullable=True),
    sa.Column('selection_reason', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('evaluation', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_attempt_child_created', ['child_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_attempts_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_attempts_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_attempts_is_correct'), ['is_correct'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_attempts_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_attempts_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_attempts_skill_id'), ['skill_id'], unique=False)

    op.create_table('question_options',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('media', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_options_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_options_question_id'))

    op.drop_table('question_options')
    with op.batch_alter_table('question_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_attempts_skill_id'))
        batch_op.drop_index(batch_op.f('ix_question_attempts_session_id'))
        batch_op.drop_index(batch_op.f('ix_question_attempts_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_attempts_is_correct'))
        batch_op.drop_index(batch_op.f('ix_question_attempts_concept_id'))
        batch_op.drop_index(batch_op.f('ix_question_attempts_child_id'))
        batch_op.drop_index('ix_attempt_child_created')

    op.drop_table('question_attempts')
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rewards_child_id'))

    op.drop_table('rewards')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_subject_id'))
        batch_op.drop_index(batch_op.f('ix_questions_skill_id'))
        batch_op.drop_index(batch_op.f('ix_questions_question_type'))
        batch_op.drop_index(batch_op.f('ix_questions_difficulty'))
        batch_op.drop_index(batch_op.f('ix_questions_concept_id'))
        batch_op.drop_index(batch_op.f('ix_questions_active'))

    op.drop_table('questions')
    with op.batch_alter_table('learner_concept_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learner_concept_states_status'))
        batch_op.drop_index(batch_op.f('ix_learner_concept_states_next_review_at'))
        batch_op.drop_index(batch_op.f('ix_learner_concept_states_concept_id'))
        batch_op.drop_index(batch_op.f('ix_learner_concept_states_child_id'))
        batch_op.drop_index('ix_learner_concept_due')

    op.drop_table('learner_concept_states')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_events_name'))
        batch_op.drop_index(batch_op.f('ix_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_events_child_id'))
        batch_op.drop_index('ix_event_child_name')

    op.drop_table('events')
    op.drop_table('concept_skills')
    op.drop_table('concept_prerequisites')
    with op.batch_alter_table('learning_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_sessions_subject_id'))
        batch_op.drop_index(batch_op.f('ix_learning_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_learning_sessions_child_id'))

    op.drop_table('learning_sessions')
    with op.batch_alter_table('learner_subject_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learner_subject_states_subject_id'))
        batch_op.drop_index(batch_op.f('ix_learner_subject_states_child_id'))

    op.drop_table('learner_subject_states')
    with op.batch_alter_table('learner_skill_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learner_skill_states_skill_id'))
        batch_op.drop_index(batch_op.f('ix_learner_skill_states_child_id'))

    op.drop_table('learner_skill_states')
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepts_subject_id'))
        batch_op.drop_index(batch_op.f('ix_concepts_slug'))
        batch_op.drop_index(batch_op.f('ix_concepts_primary_skill_id'))
        batch_op.drop_index(batch_op.f('ix_concepts_frequency_band'))

    op.drop_table('concepts')
    with op.batch_alter_table('child_milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_child_milestones_milestone_id'))
        batch_op.drop_index(batch_op.f('ix_child_milestones_child_id'))

    op.drop_table('child_milestones')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_subject_id'))
        batch_op.drop_index(batch_op.f('ix_skills_slug'))
        batch_op.drop_index(batch_op.f('ix_skills_parent_skill_id'))

    op.drop_table('skills')
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parents_family_id'))
        batch_op.drop_index(batch_op.f('ix_parents_email'))

    op.drop_table('parents')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_subject_id'))
        batch_op.drop_index(batch_op.f('ix_milestones_slug'))

    op.drop_table('milestones')
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_children_family_id'))

    op.drop_table('children')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_slug'))

    op.drop_table('subjects')
    op.drop_table('families')
    # ### end Alembic commands ###
